[package]
name = "lockpick-rs"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
derive_more = { version = "2.0.1", features = ["full"] }
simd-json = "0.15.1"
